### ISSUE TITLE
[a11y] Issue 14: Missing title element (Participation Page)

### ISSUE THREAD

**Issue by NewJerseyStyle** [NewJerseyStyle/polis#72] opened 2024-10-31 01:55 UTC
**Description:**

The participation page is missing a `<title>` element, hindering navigation and accessibility for screen reader users.

**Steps to Reproduce:**

1. Navigate to the participation page (e.g. `https://pol.is/4cvkai2ctw`)
2. Inspect the page's `<head>` section.

**Expected Behavior:**

A non-empty `<title>` element should be present.

**Actual Behavior:**

The `<title>` element is missing or empty.

**Component/Area:** Participation page

**Source:** Auto evaluation

**Affected Elements:** title

**Comment by thomassth** [comment] 2024-10-31 02:17
Should be fixed with https://github.com/CivicTechTO/polis/pull/32

**Comment by thomassth** [comment] 2024-10-31 02:23
Also duplicate of https://github.com/CivicTechTO/polis/issues/64

**Closed as completed** 2024-10-31 03:02 UTC
